services:
  frontend:
    # exposes port 8501
    build:
      context: .
      args:
        - SRC_FOLDER=${SRC_FOLDER}
      dockerfile: ./docker/frontend/Dockerfile
    container_name: ${SRC_FOLDER}-frontend
    networks:
      - network
    depends_on:
      - api
    volumes:
      - ./${SRC_FOLDER}/frontend:/app

  api:
    # exposes port 8000
    build:
      context: .
      args:
        - SRC_FOLDER=${SRC_FOLDER}
      dockerfile: ./docker/api/Dockerfile
    container_name: ${SRC_FOLDER}-api
    command:
      [
        "uvicorn",
        "neuron_viz.api.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
        "--reload-include",
        "neuron_viz/**",
      ]

    networks:
      - network
    volumes:
      - ./${SRC_FOLDER}/api:/app

  caddy:
    image: caddy:2.9.1-alpine
    container_name: ${SRC_FOLDER}-caddy
    ports:
      - "80:80" # frontend
      - "443:443" # frontend
      - "8000:8000" # api
      - "3001:3001" # brwowser-sync
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - network
    depends_on:
      - frontend

networks:
  network:
    driver: bridge
